# 相關系數

使用相關系統來檢測離群、需被注意的點  
用每個點跟點之間的距離(相關)，即可挑出需被關注的點  
但當維度愈來愈多後，會有「維度的詛咒」現像，距離變得愈來愈不明顯。

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
df1 = pd.read_csv('hpv1.csv')
df2 = pd.read_csv('hpv2.csv')
df3 = pd.read_csv('hpv3.csv')
df4 = pd.read_csv('hpv4.csv')
df5 = pd.read_csv('hpv5.csv')
df6 = pd.read_csv('hpv6.csv')
df7 = pd.read_csv('hpv7.csv')
df8 = pd.read_csv('hpv8.csv')

op1 = df1.iloc[:,1:3]
op2 = df2.iloc[:,1:3]
op3 = df3.iloc[:,1:3]
op4 = df4.iloc[:,1:3]
op5 = df5.iloc[:,1:3]
op6 = df6.iloc[:,1:3]
op7 = df7.iloc[:,1:3]
op8 = df8.iloc[:,1:3]

op1.head()

   2017-09-23 05:00:00     0
0  2017-09-23 06:00:00  0.23
1  2017-09-23 07:00:00  0.59
2  2017-09-23 08:00:00  1.79
3  2017-09-23 09:00:00  2.75
4  2017-09-23 09:00:00  2.75

In [22]:
op2.head()

   2017-09-23 05:00:00     0
0  2017-09-23 06:00:00  0.20
1  2017-09-23 07:00:00  0.57
2  2017-09-23 08:00:00  1.78
3  2017-09-23 09:00:00  2.51
4  2017-09-23 10:00:00  3.28

In [6]:
opx = pd.concat([op1, op2, op3, op4, op5, op6, op7, op8], axis=1)

plt.plot(op1)
plt.plot(op2)
plt.plot(op3)
plt.plot(op4)
plt.plot(op5)
plt.plot(op6)
plt.plot(op7)
plt.plot(op8)

plt.show()

In [7]:
opx

       0     0     0     0     0     0     0     0
0   0.23  0.20  0.23  0.22  0.22  0.25  0.20  0.20
1   0.59  0.57  0.60  0.58  0.58  0.66  0.52  0.52
2   1.79  1.78  1.83  1.79  1.78  2.03  1.60  1.58
3   2.75  2.51  2.80  2.74  2.74  3.11  2.47  2.44
4   2.75  3.28  3.54  3.50  3.49  3.96  3.16  3.10
5   3.49  3.82  3.87  3.83  3.82  4.34  3.46  3.41
6   3.82  2.34  2.59  2.56  2.55  2.88  2.30  2.25
7   2.56  3.17  3.23  3.21  3.19  3.61  2.88  2.82
8   3.20  2.51  2.55  2.53  2.52  2.84  2.26  2.22
9   2.52  1.77  1.80  1.77  1.76  1.99  1.58  1.56
10  1.78  0.82  0.85  0.84  0.83  0.94  0.74  0.73
11  0.84  0.10  0.13  0.12  0.12  0.13  0.10  0.10
12  0.12  0.10  0.13  0.12  0.12  0.13  0.10  0.10
13  0.12  0.10  0.13  0.12  0.12  0.13  0.10  0.10
14  0.12  0.00  0.00  0.00  0.00  0.00  0.00  0.00
15  0.00  0.23  0.26  0.25  0.25  0.29  0.23  0.23
16  0.25  1.22  1.26  1.21  1.22  1.39  1.09  1.08
17  1.23  2.24  2.29  2.23  2.24  2.55  2.02  1.99
18  2.25  2.40  2.72  2.67  2.67  2.64  2.41  2.37
19  2.68  1.19  2.48  2.44  2.43  1.23  2.18  2.14
20  2.46  1.94  3.13  3.09  3.09  2.76  2.78  2.75
21  3.07  3.12  3.74  3.70  3.66  4.11  3.28  3.28
22  3.67  3.46  3.51  3.47  3.44  3.88  3.08  3.07
23  3.46  2.92  2.97  2.94  2.91  3.29  2.60  2.59
24  2.93  2.17  2.20  2.19  2.15  2.43  1.93  1.92
25  2.18  0.96  1.00  0.98  0.96  1.09  0.86  0.84
26  0.99  0.17  0.20  0.19  0.18  0.21  0.16  0.16
27  0.19  0.17  0.20  0.19  0.18  0.21  0.16  0.16
28  0.19  0.17  0.20  0.19  0.18  0.21  0.16  0.16
29  0.19  0.00  0.00  0.00  0.00  0.00  0.00  0.00
30  0.00  0.25  0.28  0.27  0.28  0.31  0.25  0.24
31  0.28  1.29  1.33  1.29  1.30  1.48  1.17  1.15
32  1.30  2.39  2.44  2.38  2.38  2.71  2.14  2.11
33  2.40  1.46  1.50  1.47  1.47  1.66  1.32  1.30
34  1.48  0.99  1.18  1.15  1.16  1.30  1.04  1.03
35  1.15   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [13]:
opx.corr()

,0,0,0,0,0,0,0,0
0,1.000000,0.852902,0.869105,0.871337,0.869071,0.851034,0.868058,0.868118
0,0.852902,1.000000,0.973783,0.973910,0.973651,0.994617,0.973811,0.973848
0,0.869105,0.973783,1.000000,0.999953,0.999970,0.979773,0.999919,0.999952
0,0.871337,0.973910,0.999953,1.000000,0.999959,0.979915,0.999906,0.999946
0,0.869071,0.973651,0.999970,0.999959,1.000000,0.979718,0.999975,0.999966
0,0.851034,0.994617,0.979773,0.979915,0.979718,1.000000,0.979862,0.980201
0,0.868058,0.973811,0.999919,0.999906,0.999975,0.979862,1.000000,0.999937
0,0.868118,0.973848,0.999952,0.999946,0.999966,0.980201,0.999937,1.000000

In [7]:
op1

0     0.23
1     0.59
2     1.79
3     2.75
4     2.75
5     3.49
6     3.82
7     2.56
8     3.20
9     2.52
10    1.78
11    0.84
12    0.12
13    0.12
14    0.12
15    0.00
16    0.25
17    1.23
18    2.25
19    2.68
20    2.46
21    3.07
22    3.67
23    3.46
24    2.93
25    2.18
26    0.99
27    0.19
28    0.19
29    0.19
30    0.00
31    0.28
32    1.30
33    2.40
34    1.48
35    1.15
Name: 0, dtype: float64

In [18]:
df1.iloc[:,1:3]

    2017-09-23 05:00:00     0
0   2017-09-23 06:00:00  0.23
1   2017-09-23 07:00:00  0.59
2   2017-09-23 08:00:00  1.79
3   2017-09-23 09:00:00  2.75
4   2017-09-23 09:00:00  2.75
5   2017-09-23 10:00:00  3.49
6   2017-09-23 11:00:00  3.82
7   2017-09-23 12:00:00  2.56
8   2017-09-23 13:00:00  3.20
9   2017-09-23 14:00:00  2.52
10  2017-09-23 15:00:00  1.78
11  2017-09-23 16:00:00  0.84
12  2017-09-23 17:00:00  0.12
13  2017-09-23 17:00:00  0.12
14  2017-09-23 17:00:00  0.12
15  2017-09-24 05:00:00  0.00
16  2017-09-24 06:00:00  0.25
17  2017-09-24 07:00:00  1.23
18  2017-09-24 08:00:00  2.25
19  2017-09-24 09:00:00  2.68
20  2017-09-24 10:00:00  2.46
21  2017-09-24 11:00:00  3.07
22  2017-09-24 12:00:00  3.67
23  2017-09-24 13:00:00  3.46
24  2017-09-24 14:00:00  2.93
25  2017-09-24 15:00:00  2.18
26  2017-09-24 16:00:00  0.99
27  2017-09-24 17:00:00  0.19
28  2017-09-24 17:00:00  0.19
29  2017-09-24 17:00:00  0.19
30  2017-09-25 05:00:00  0.00
31  2017-09-25 06:00:00  0.28
32  2017-09-25 07:00:00  1.30
33  2017-09-25 08:00:00  2.40
34  2017-09-25 09:00:00  1.48
35  2017-09-25 10:00:00  1.15

In [15]:
df2

,2,2017-09-23 05:00:00,0,232.2,0.1,0.2,59.9,0.3,0.4,0.5,...,234,0.6,0.7,245.7,0.8,27.3,30.8,0.9,0.10,615
0,2,2017-09-23 06:00:00,0.20,232.5,0,0,59.9,1.2,0,0,...,284.2,0.4,0.4,366.5,0,29.4,33.4,0.1,0.1,616
1,2,2017-09-23 07:00:00,0.57,233.1,0,0,59.9,2.5,0,0,...,278.9,1.1,1.1,374.6,0,32.6,37.2,0.3,0.3,616
2,2,2017-09-23 08:00:00,1.78,235.3,0,0,60.0,7.6,0,0,...,266.0,3.6,3.6,377.7,0,40.0,45.1,0.9,0.9,618
3,2,2017-09-23 09:00:00,2.51,235.2,0,0,59.9,10.6,0,0,...,261.3,5.2,5.2,373.1,0,47.9,53.6,1.3,1.3,621
4,2,2017-09-23 10:00:00,3.28,235.0,0,0,59.9,13.9,0,0,...,259.6,6.7,6.7,372.4,0,50.5,56.8,1.7,1.7,624
5,2,2017-09-23 11:00:00,3.82,235.1,0,0,59.9,16.2,0,0,...,251.9,7.8,7.8,377.3,0,55.1,61.5,1.9,1.9,628
6,2,2017-09-23 12:00:00,2.34,233.7,0,0,59.9,10.0,0,0,...,262.8,4.8,4.8,371.0,0,49.0,55.0,1.2,1.2,630
7,2,2017-09-23 13:00:00,3.17,234.8,0,0,60.0,13.5,0,0,...,254.7,6.5,6.5,376.9,0,50.0,56.4,1.6,1.6,633
8,2,2017-09-23 14:00:00,2.51,233.2,0,0,60.0,10.7,0,0,...,261.9,5.1,5.1,374.8,0,48.6,54.6,1.3,1.3,635
9,2,2017-09-23 15:00:00,1.77,232.6,0,0,59.9,7.6,0,0,...,268.6,3.5,3.5,373.8,0,44.0,49.4,0.9,0.9,637
10,2,2017-09-23 16:00:00,0.82,232.3,0,0,59.9,3.6,0,0,...,275.2,1.7,1.7,373.6,0,39.1,44.0,0.4,0.4,638
11,2,2017-09-23 17:00:00,0.10,231.7,0,0,59.9,1.0,0,0,...,276.8,0.2,0.2,372.7,0,35.0,39.5,0.1,0.1,638
12,2,2017-09-23 17:00:00,0.10,231.7,0,0,59.9,1.0,0,0,...,276.8,0.2,0.2,372.7,0,35.0,39.5,0.1,0.1,638
13,2,2017-09-23 17:00:00,0.10,231.7,0,0,59.9,1.0,0,0,...,276.8,0.2,0.2,372.7,0,35.0,39.5,0.1,0.1,638
14,2,2017-09-24 05:00:00,0.00,231.6,0,0,59.9,0.0,0,0,...,224.0,0.0,0.0,231.2,0,27.2,30.6,0.0,0.0,638
15,2,2017-09-24 06:00:00,0.23,232.0,0,0,59.9,1.3,0,0,...,283.2,0.5,0.5,360.3,0,29.3,33.3,0.1,0.1,638
16,2,2017-09-24 07:00:00,1.22,233.6,0,0,60.0,5.2,0,0,...,275.6,2.4,2.4,375.4,0,35.0,39.6,0.6,0.7,640
17,2,2017-09-24 08:00:00,2.24,237.4,0,0,59.9,9.4,0,0,...,263.1,4.5,4.5,380.6,0,43.0,48.5,1.2,1.2,642
18,2,2017-09-24 09:00:00,2.40,236.5,0,0,59.9,10.1,0,0,...,264.3,4.9,4.9,371.9,0,48.0,53.6,1.2,1.3,644
19,2,2017-09-24 10:00:00,1.19,234.8,0,0,59.9,5.0,0,0,...,283.9,2.5,2.5,351.3,0,43.8,49.0,0.6,0.6,645
20,2,2017-09-24 11:00:00,1.94,235.1,0,0,60.0,8.2,0,0,...,281.0,4.0,4.0,354.3,0,43.4,48.9,1.0,1.0,647
21,2,2017-09-24 12:00:00,3.12,235.3,0,0,59.9,13.2,0,0,...,258.4,6.4,6.4,369.1,0,49.5,55.6,1.6,1.6,650
22,2,2017-09-24 13:00:00,3.46,234.8,0,0,59.9,14.7,0,0,...,250.1,7.0,7.0,376.9,0,53.2,59.7,1.8,1.7,654
23,2,2017-09-24 14:00:00,2.92,234.2,0,0,59.9,12.4,0,0,...,253.7,6.0,6.0,376.1,0,51.7,58.1,1.5,1.5,657
24,2,2017-09-24 15:00:00,2.17,234.1,0,0,59.9,9.2,0,0,...,262.9,4.4,4.4,375.9,0,47.5,53.2,1.1,1.1,659
25,2,2017-09-24 16:00:00,0.96,233.1,0,0,60.0,4.2,0,0,...,272.9,1.9,1.9,374.6,0,40.7,46.0,0.5,0.5,660
26,2,2017-09-24 17:00:00,0.17,231.6,0,0,60.0,1.1,0,0,...,278.2,0.4,0.4,372.5,0,36.2,40.8,0.1,0.1,660
27,2,2017-09-24 17:00:00,0.17,231.6,0,0,60.0,1.1,0,0,...,278.2,0.4,0.4,372.5,0,36.2,40.8,0.1,0.1,660
28,2,2017-09-24 17:00:00,0.17,231.6,0,0,60.0,1.1,0,0,...,278.2,0.4,0.4,372.5,0,36.2,40.8,0.1,0.1,660
29,2,2017-09-25 05:00:00,0.00,231.0,0,0,59.9,0.0,0,0,...,284.0,0.0,0.0,281.6,0,27.6,31.0,0.0,0.0,660
30,2,2017-09-25 06:00:00,0.25,231.4,0,0,60.0,1.3,0,0,...,287.5,0.5,0.5,364.7,0,29.6,33.7,0.1,0.1,660
31,2,2017-09-25 07:00:00,1.29,233.6,0,0,60.0,5.5,0,0,...,273.3,2.6,2.6,375.3,0,35.9,40.5,0.7,0.7,662
32,2,2017-09-25 08:00:00,2.39,235.3,0,0,59.9,10.2,0,0,...,262.2,4.8,4.8,377.5,0,43.4,48.9,1.2,1.3,664
33,2,2017-09-25 09:00:00,1.46,232.7,0,0,59.9,6.3,0,0,...,267.2,3.0,3.0,374.0,0,44.1,49.4,0.7,0.8,665
34,2,2017-09-25 10:00:00,0.99,231.8,0,0,59.9,4.3,0,0,...,273.7,2.0,2.0,368.2,0,39.8,44.9,0.5,0.5,666

In [16]:
df3

,3,2017-09-23 05:00:00,0,239.7,0.1,0.2,60,0.5,0.3,0.4,...,246.9,0.5.1,0.6,301.8,0.7,27.8,31.3,0.8,0.9,713
0,3,2017-09-23 06:00:00,0.23,240.1,0,0,60.0,1.3,0,0,...,264.8,0.5,0.6,382.8,0,30.3,34.5,0.1,0.1,713
1,3,2017-09-23 07:00:00,0.60,240.4,0,0,59.9,2.6,0,0,...,267.8,1.2,1.3,385.1,0,33.8,38.3,0.3,0.3,714
2,3,2017-09-23 08:00:00,1.83,242.5,0,0,59.9,7.5,0,0,...,265.0,3.5,3.8,387.8,0,40.9,46.2,0.9,1.0,716
3,3,2017-09-23 09:00:00,2.80,243.1,0,0,59.9,11.5,0,0,...,257.8,5.5,5.9,388.7,0,49.4,55.4,1.4,1.5,719
4,3,2017-09-23 10:00:00,3.54,243.1,0,0,60.0,14.5,0,0,...,255.9,7.0,7.5,388.7,0,52.9,59.4,1.7,1.9,722
5,3,2017-09-23 11:00:00,3.87,243.4,0,0,59.9,15.9,0,0,...,252.8,7.6,8.3,389.1,0,56.3,62.8,1.9,2.1,726
6,3,2017-09-23 12:00:00,2.59,242.6,0,0,59.9,10.6,0,0,...,261.5,5.1,5.4,387.9,0,50.8,57.0,1.3,1.4,729
7,3,2017-09-23 13:00:00,3.23,243.9,0,0,60.0,13.2,0,0,...,258.0,6.3,6.8,389.8,0,51.1,57.7,1.6,1.7,732
8,3,2017-09-23 14:00:00,2.55,242.2,0,0,60.0,10.5,0,0,...,262.3,5.0,5.3,387.4,0,49.8,55.8,1.3,1.4,734
9,3,2017-09-23 15:00:00,1.80,241.1,0,0,59.9,7.4,0,0,...,267.3,3.5,3.7,385.9,0,45.2,50.7,0.9,1.0,736
10,3,2017-09-23 16:00:00,0.85,240.5,0,0,59.9,3.6,0,0,...,267.7,1.7,1.8,385.0,0,40.2,45.3,0.4,0.5,737
11,3,2017-09-23 17:00:00,0.13,240.1,0,0,59.9,1.2,0,0,...,256.2,0.3,0.3,384.5,0,36.2,40.7,0.1,0.1,737
12,3,2017-09-23 17:00:00,0.13,240.1,0,0,59.9,1.2,0,0,...,256.2,0.3,0.3,384.5,0,36.2,40.7,0.1,0.1,737
13,3,2017-09-23 17:00:00,0.13,240.1,0,0,59.9,1.2,0,0,...,256.2,0.3,0.3,384.5,0,36.2,40.7,0.1,0.1,737
14,3,2017-09-24 05:00:00,0.00,238.9,0,0,60.0,0.6,0,0,...,257.0,0.0,0.0,327.5,0,27.8,31.4,0.0,0.0,737
15,3,2017-09-24 06:00:00,0.26,239.4,0,0,59.9,1.5,0,0,...,268.6,0.5,0.6,379.9,0,30.2,34.5,0.1,0.2,737
16,3,2017-09-24 07:00:00,1.26,240.7,0,0,60.0,5.2,0,0,...,272.0,2.4,2.6,385.4,0,36.1,40.7,0.6,0.7,739
17,3,2017-09-24 08:00:00,2.29,244.2,0,0,59.9,9.4,0,0,...,263.2,4.4,4.8,390.2,0,44.0,49.6,1.2,1.2,741
18,3,2017-09-24 09:00:00,2.72,243.7,0,0,59.9,11.2,0,0,...,260.1,5.3,5.7,389.5,0,49.5,55.5,1.4,1.5,744
19,3,2017-09-24 10:00:00,2.48,242.7,0,0,59.9,10.2,0,0,...,259.7,4.8,5.2,388.2,0,50.1,56.1,1.2,1.3,746
20,3,2017-09-24 11:00:00,3.13,243.3,0,0,60.0,12.8,0,0,...,258.2,6.1,6.6,389.0,0,50.5,56.8,1.6,1.7,749
21,3,2017-09-24 12:00:00,3.74,244.1,0,0,59.9,15.3,0,0,...,253.2,7.3,7.9,389.9,0,54.6,61.2,1.9,2.0,753
22,3,2017-09-24 13:00:00,3.51,243.9,0,0,59.9,14.4,0,0,...,253.0,6.9,7.4,389.6,0,55.3,61.8,1.7,1.9,757
23,3,2017-09-24 14:00:00,2.97,243.2,0,0,60.0,12.2,0,0,...,256.6,5.8,6.2,388.9,0,53.0,59.5,1.5,1.6,759
24,3,2017-09-24 15:00:00,2.20,243.0,0,0,59.9,9.0,0,0,...,264.0,4.3,4.5,388.5,0,48.3,54.1,1.1,1.2,762
25,3,2017-09-24 16:00:00,1.00,241.8,0,0,60.0,4.2,0,0,...,267.6,1.9,2.1,386.9,0,41.5,46.9,0.5,0.6,763
26,3,2017-09-24 17:00:00,0.20,240.6,0,0,60.0,1.3,0,0,...,257.9,0.5,0.5,385.2,0,37.4,41.9,0.1,0.1,763
27,3,2017-09-24 17:00:00,0.20,240.6,0,0,60.0,1.3,0,0,...,257.9,0.5,0.5,385.2,0,37.4,41.9,0.1,0.1,763
28,3,2017-09-24 17:00:00,0.20,240.6,0,0,60.0,1.3,0,0,...,257.9,0.5,0.5,385.2,0,37.4,41.9,0.1,0.1,763
29,3,2017-09-25 05:00:00,0.00,239.1,0,0,59.9,0.5,0,0,...,265.8,0.0,0.0,327.4,0,28.8,32.2,0.0,0.0,763
30,3,2017-09-25 06:00:00,0.28,239.0,0,0,60.0,1.5,0,0,...,270.1,0.6,0.6,379.4,0,30.6,34.9,0.2,0.2,763
31,3,2017-09-25 07:00:00,1.33,240.8,0,0,60.0,5.5,0,0,...,270.9,2.5,2.7,385.4,0,36.8,41.5,0.7,0.7,764
32,3,2017-09-25 08:00:00,2.44,241.9,0,0,59.9,10.1,0,0,...,263.8,4.7,5.0,387.0,0,44.3,49.9,1.2,1.3,767
33,3,2017-09-25 09:00:00,1.50,240.1,0,0,59.9,6.2,0,0,...,263.2,3.0,3.2,384.5,0,45.0,50.6,0.8,0.8,768
34,3,2017-09-25 10:00:00,1.18,238.8,0,0,59.9,4.9,0,0,...,267.5,2.3,2.4,382.8,0,41.1,46.7,0.6,0.6,770